name: Napkin CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

permissions:
  contents: read

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    name: "Spellcheck"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade codespell
      - name: Run spellcheck
        run: |
          codespell $(git ls-files '*.tex')

  build:
    runs-on: ubuntu-latest
    name: "Compile document"
    permissions:
      actions: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install TeX Live
        run: |
          sudo apt update
          sudo apt install -y biber texlive-base texlive-latex-recommended texlive-latex-extra texlive-science
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install more packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: |
            latexmk asymptote ghostscript qpdf

      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          key: "napkin-cache"
          path: |
            **/*.aux
            **/*.out
            Napkin.bbl
            Napkin.bcf
            Napkin.blg
            Napkin.fdb_latexmk
            Napkin.fls
            Napkin.log
            Napkin.maf
            Napkin.mtc
            Napkin.mtc0
            Napkin.pre
            Napkin.ptc*
            Napkin.run.xml
            Napkin.synctex.gz
            Napkin.toc
            asy/Napkin-*.asy
            asy/Napkin-*.pdf
      - name: Compile document
        run: latexmk -pdflatex -interaction=nonstopmode -file-line-error Napkin.tex
      - name: Save cache
        uses: actions/cache/save@v4
        with:
          key: "napkin-cache"
          path: |
            **/*.aux
            **/*.out
            Napkin.bbl
            Napkin.bcf
            Napkin.blg
            Napkin.fdb_latexmk
            Napkin.fls
            Napkin.log
            Napkin.maf
            Napkin.mtc
            Napkin.mtc0
            Napkin.pre
            Napkin.ptc*
            Napkin.run.xml
            Napkin.synctex.gz
            Napkin.toc
            asy/Napkin-*.asy
            asy/Napkin-*.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          path: Napkin.pdf
          name: Napkin.pdf
